from app.services.statistics.anomaly import (
    detect_anomalies,
    detect_iqr_anomalies,
    iqr_bounds,
)
from app.services.statistics.causal_inference import GrangerConfig, granger_causality
from app.services.statistics.changepoint import ChangepointConfig, detect_changepoints
from app.services.statistics.growth_engine import (
    GrowthEngineConfig,
    compute_growth_context,
    compute_growth_signals,
    metric_growth_config,
)
from app.services.statistics.multivariate import (
    MultivariateConfig,
    compute_multivariate_context,
)
from app.services.statistics.leading_indicators import (
    LeadingIndicatorConfig,
    detect_leading_indicators,
)
from app.services.statistics.base_projection import (
    BaseProjectionConfig,
    align_growth_to_periods,
    build_projection_periods,
    cagr_growth,
    compute_growth_rates,
    project_base_case,
    project_revenue_from_growth,
    rolling_average_growth,
)
from app.services.statistics.inflation_adjustment import (
    align_cpi_to_kpi_periods,
    build_inflation_adjusted_series,
    compound_inflation_rates,
    compute_cpi_inflation_rate,
    compute_inflation_adjusted_revenue,
    compute_real_growth_rate as compute_real_growth_rate_with_cpi,
)
from app.services.statistics.macro_normalizer import (
    align_macro_series_to_periods,
    compute_growth_from_levels,
    compute_growth_vs_gdp_delta,
    compute_rate_adjusted_efficiency,
    compute_real_growth_rate,
    normalize_business_metrics_for_macro,
    normalize_rate_series,
)
from app.services.statistics.normalization import (
    MetricStatisticsConfig,
    metric_statistics_config,
    rolling_mean,
    rolling_median,
    zscore_normalize,
)
from app.services.statistics.scenario_simulator import (
    ScenarioConfig,
    ScenarioShock,
    simulate_deterministic_scenarios,
)
from app.services.statistics.survival_analysis import (
    SurvivalConfig,
    kaplan_meier,
    survival_from_retention_curve,
)
from app.services.statistics.recession_modeling import (
    RecessionCurveProfile,
    RecessionModelConfig,
    build_recovery_multiplier_curve,
    compute_revenue_shock_multiplier,
    extract_macro_shock_inputs,
    model_recession_projection,
)
from app.services.statistics.market_share_simulation import (
    MarketScenarioAssumption,
    MarketShareSimulationConfig,
    simulate_market_share,
)
from app.services.statistics.scenario_orchestration import (
    ScenarioOrchestrationConfig,
    ScenarioToggles,
    orchestrate_all_scenarios,
    orchestrate_scenarios_batch,
    orchestrate_scenario,
    run_base_scenario,
    run_combined_scenario,
    run_erosion_scenario,
    run_recession_scenario,
)
from app.services.statistics.competitive_erosion import (
    CompetitiveErosionConfig,
    apply_erosion_to_growth,
    compute_erosion_curve,
    project_market_share,
    score_to_vulnerability,
    simulate_competitive_erosion,
)

__all__ = [
    "MetricStatisticsConfig",
    "metric_statistics_config",
    "zscore_normalize",
    "rolling_mean",
    "rolling_median",
    "iqr_bounds",
    "detect_iqr_anomalies",
    "detect_anomalies",
    "GrangerConfig",
    "granger_causality",
    "ChangepointConfig",
    "detect_changepoints",
    "GrowthEngineConfig",
    "metric_growth_config",
    "compute_growth_signals",
    "compute_growth_context",
    "MultivariateConfig",
    "compute_multivariate_context",
    "LeadingIndicatorConfig",
    "detect_leading_indicators",
    "BaseProjectionConfig",
    "compute_growth_rates",
    "cagr_growth",
    "rolling_average_growth",
    "build_projection_periods",
    "align_growth_to_periods",
    "project_revenue_from_growth",
    "project_base_case",
    "align_cpi_to_kpi_periods",
    "compute_cpi_inflation_rate",
    "compute_real_growth_rate_with_cpi",
    "compute_inflation_adjusted_revenue",
    "compound_inflation_rates",
    "build_inflation_adjusted_series",
    "compute_growth_from_levels",
    "normalize_rate_series",
    "align_macro_series_to_periods",
    "compute_real_growth_rate",
    "compute_growth_vs_gdp_delta",
    "compute_rate_adjusted_efficiency",
    "normalize_business_metrics_for_macro",
    "ScenarioConfig",
    "ScenarioShock",
    "simulate_deterministic_scenarios",
    "SurvivalConfig",
    "kaplan_meier",
    "survival_from_retention_curve",
    "RecessionCurveProfile",
    "RecessionModelConfig",
    "extract_macro_shock_inputs",
    "compute_revenue_shock_multiplier",
    "build_recovery_multiplier_curve",
    "model_recession_projection",
    "MarketScenarioAssumption",
    "MarketShareSimulationConfig",
    "simulate_market_share",
    "ScenarioToggles",
    "ScenarioOrchestrationConfig",
    "orchestrate_scenario",
    "orchestrate_all_scenarios",
    "orchestrate_scenarios_batch",
    "run_base_scenario",
    "run_erosion_scenario",
    "run_recession_scenario",
    "run_combined_scenario",
    "CompetitiveErosionConfig",
    "score_to_vulnerability",
    "compute_erosion_curve",
    "apply_erosion_to_growth",
    "project_market_share",
    "simulate_competitive_erosion",
]
